% CONSTRUCTION OF THE RESPONSE MATRIX R AND THE SOURCE VECTOR P FOR THE
% ITERATIVE PROCESS

function [R, ...  % RESPONSE MATRIX FOR THE ITERATIVE PROCESS
          P, ...  % SOURCE VECTOR FOR THE ITERATIVE PROCESS
          RM, ... % RESPONSE MATRIZ FOR THE RECONSTRUCTION OF THE AVERAGE
              ... % ANGULAR FLUXES IN EACH NODE
          LM1,... % LEAKAGE MATRIX 1 FOR THE RECONTRUCTION OF THE AVERAGE 
              ... % ANGULAR FLUXES IN EACH NODE
          LM2,... % LEAKAGE MATRIX 2 FOR THE RECONTRUCTION OF THE AVERAGE 
              ... % ANGULAR FLUXES IN EACH NODE
          PM  ... % SOURCE VECTOR FOR THE RECONSTRUCTION OF THE AVERAGE 
              ... % ANGULAR FLUXES IN EACH NODE
          ] = response_matrix(N, ZON, XDOM, YDOM, ZMAP, QMAP)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% SHORTHAND
% R(m, k, JB, IB)   P(m, JB, IB)
% RM(m, k, JB, IB)  LM1(m, k, JB, IB) LM2(m, k, JB, IB) PM(m, JB, IB)
  
  % INITIALIZE VARIABLES
  NRX = length(XDOM(1, :)); NRY = length(YDOM(1, :));
  I = sum(XDOM(2, :));      J = sum(YDOM(2, :));
  
  % QUADRATURE SET
  [QUAD, chi] = LQN_2D(N);
  
  % LANDA PARAMETERS
  [LANDA0, LANDAL, LANDAR, LANDAB, LANDAT] = landa(XDOM, YDOM, ZON, ZMAP);
  [XD0, XDB, XDT, YD0, YDL, YDR, XN0, XNB, XNT, YN0, YNL, YNR] = ...
   constants(QUAD, ZON, XDOM, YDOM, ZMAP, LANDA0, LANDAB, LANDAT, LANDAL, LANDAR);
  
  % EIGENVALUES AND EIGENVECTORS
  [xvals, xvects, yvals, yvects] = SPECTRUM_XY(QUAD, chi, ZON);
  
  % RESPONSE MATRIX AND SOURCE VECTOR
  M = N * (N + 2) / 2;
  R = zeros(2 * M, 2 * M, J, I); P = zeros(2 * M, J, I);
  RM = zeros(M, M, J, I); LM1 = zeros(M, M, J, I);
  LM2 = zeros(M, M, J, I); PM = zeros(M, J, I);
  
  % AUXILIARY MATRICES
  XA = zeros(M, M); YA = zeros(M, M); XE = zeros(M, M); YE = zeros(M, M); 
  XM = zeros(M, M);
  XB_OUT = zeros(M, M); XB_IN = zeros(M, M); XC_OUT = zeros(M, M); XC_IN = zeros(M, M);
  YB_OUT = zeros(M, M); YB_IN = zeros(M, M); YC_OUT = zeros(M, M); YC_IN = zeros(M, M);
  MB = zeros(M, M);     MC = zeros(M, M);    IDEN = eye(M, M);     H = zeros(M, 1);
  
  % DEFINE EACH MATRIX PER REGION
  JB = 0;
  for ry = 1: NRY
    leny = YDOM(1, ry); ncy = YDOM(2, ry); hy = leny / ntcy;
    for j = 1: ncy
      JB = JB + 1;
      IB = 0;
      for rx = 1: NRX
    
        % AUXILIARY PARAMETERS
        lenx = XDOM(1, rx); ncx = XDOM(2, rx); hx = lenx / ntcx;
        z = ZMAP(ry, rx); st = ZON(1, z); ss = ZON(2, z); c0 = ss/st;
        Q = QMAP(ry, rx);
        for i = 1: ncx
          IB = IB + 1;
          for m = 1: M %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% LOOP FOR THE ROWS
            m_miu = QUAD(m, 1); m_theta = QUAD(m, 2);
            
            if (m <= M / 4) %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% IQ
              for k = 1: M  % LOOP FOR THE COLUMNS (IQ)
                k_miu = QUAD(k, 1); k_theta = QUAD(k, 2); k_w = QUAD(k, 3);
                
                XA(m, k) = xvects(m, k, z) * exp(0.5 * st * hx / xvals(k, z));
                XE(m, k) = xvects(m, k, z) * exp(- 0.5 * st * hx / xvals(k, z));
                YA(m, k) = yvects(m, k, z) * exp(0.5 * st * hy / yvals(k, z));
                YE(m, k) = yvects(m, k, z) * exp(- 0.5 * st * hy / yvals(k, z));
                XM(m, k) = xvects(m, k, z) * xvals(k, z) * 2 * sinh(0.5 * st * hx / xvals(k, z)) / (st * hx);
                
                if (k <= M / 4) % IQ
                  XB_OUT(m, k) = - 0.25 * ss * XN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st - k_miu * LANDA0(JB, IB)));
                  if (k == m) 
                      XB_OUT(m, k) = XB_OUT(m,k) - XN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hx) ...
                                     * m_theta / (hy * (st - m_miu * LANDA0(JB, IB)));
                  end
                  
                  MB(m, k) = - 0.25 * ss * XN0(JB, IB) * (2 * sinh(0.5 * LANDA0(JB, IB) * hx)/(LANDA0(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st - m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st - k_miu * LANDA0(JB, IB)));
                  if (k == m) 
                      MB(m, k) = MB(m,k) - XN0(JB, IB) * (2 * sinh(0.5 * LANDA0(JB, IB) * hx)/(LANDA0(JB, IB) * hx)) ...
                                     * m_theta / (hy * (st - m_miu * LANDA0(JB, IB)));
                  end
                  
                  XB_IN(m, k) = - 0.25 * ss * XN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st - k_miu * LANDA0(JB, IB)));
                  if (k == m) 
                      XB_IN(m, k) = XB_IN(m,k) - XN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hx) ...
                                     * m_theta / (hy * (st - m_miu * LANDA0(JB, IB)));
                  end
                  
                  XC_OUT(m, k) = + 0.25 * ss * XNB(JB, IB) * exp(- 0.5 * LANDAB(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDAB(JB, IB)) * XDB(JB, IB) ...
                                 * hy * (st - k_miu * LANDAB(JB, IB)));
                  if (k == m) 
                      XC_OUT(m, k) = XC_OUT(m,k) + XNB(JB, IB) * exp(- 0.5 * LANDAB(JB, IB) * hx) ...
                                     * m_theta / (hy * (st - m_miu * LANDAB(JB, IB)));
                  end
                  
                  MC(m, k) = + 0.25 * ss * XNB(JB, IB) * (2 * sinh(0.5 * LANDAB(JB, IB) * hx)/(LANDAB(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st - m_miu * LANDAB(JB, IB)) * XDB(JB, IB) ...
                                 * hy * (st - k_miu * LANDAB(JB, IB)));
                  if (k == m) 
                      MC(m, k) = MC_OUT(m,k) + XNB(JB, IB) * (2 * sinh(0.5 * LANDAB(JB, IB) * hx)/(LANDAB(JB, IB) * hx)) ...
                                     * m_theta / (hy * (st - m_miu * LANDAB(JB, IB)));
                  end
                  
                  XC_IN(m, k) = + 0.25 * ss * XNB(JB, IB) * exp(0.5 * LANDAB(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDAB(JB, IB)) * XDB(JB, IB) ...
                                 * hy * (st - k_miu * LANDAB(JB, IB)));
                  if (k == m) 
                      XC_IN(m, k) = XC_IN(m,k) + XNB(JB, IB) * exp(0.5 * LANDAB(JB, IB) * hx) ...
                                     * m_theta / (hy * (st - m_miu * LANDAB(JB, IB)));
                  end
                  
                  YB_OUT(m, k) = - 0.25 * ss * YN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st - k_theta * LANDA0(JB, IB)));
                  if (k == m) 
                    YB_OUT(m, k) = YB_OUT(m,k) - YN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hy) ...
                                   * m_miu / (hx * (st - m_theta * LANDA0(JB, IB)));
                  end
                  
                  YB_IN(m, k) = - 0.25 * ss * YN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st - k_theta * LANDA0(JB, IB)));
                  if (k == m) 
                    YB_IN(m, k) = YB_IN(m,k) - YN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hy) ...
                                   * m_miu / (hx * (st - m_theta * LANDA0(JB, IB)));
                  end
                  
                  YC_OUT(m, k) = + 0.25 * ss * YNL(JB, IB) * exp(- 0.5 * LANDAL(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDAL(JB, IB)) * YDL(JB, IB) ...
                                 * hx * (st - k_theta * LANDAL(JB, IB)));
                  if (k == m) 
                    YC_OUT(m, k) = YC_OUT(m,k) + YNL(JB, IB) * exp(- 0.5 * LANDAL(JB, IB) * hy) ...
                                   * m_miu / (hx * (st - m_theta * LANDAL(JB, IB)));
                  end
                  
                  YC_IN(m, k) = + 0.25 * ss * YNL(JB, IB) * exp(0.5 * LANDAL(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDAL(JB, IB)) * YDL(JB, IB) ...
                                 * hx * (st - k_theta * LANDAL(JB, IB)));
                  if (k == m) 
                    YC_IN(m, k) = YC_IN(m,k) + YNL(JB, IB) * exp(0.5 * LANDAL(JB, IB) * hy) ...
                                   * m_miu / (hx * (st - m_theta * LANDAL(JB, IB)));
                  end
                  
                elseif (k > M / 4 && k <= M / 2) % IIQ
                  XB_OUT(m, k) = - 0.25 * ss * XN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st + k_miu * LANDA0(JB, IB)));
                             
                  MB(m, k) = - 0.25 * ss * XN0(JB, IB) * (2 * sinh(0.5 * LANDA0(JB, IB) * hx)/(LANDA0(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st + m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st + k_miu * LANDA0(JB, IB)));
                  
                  XB_IN(m, k) = - 0.25 * ss * XN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st + k_miu * LANDA0(JB, IB)));
                             
                  XC_OUT(m, k) = + 0.25 * ss * XNB(JB, IB) * exp(0.5 * LANDAB(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDAB(JB, IB)) * XDB(JB, IB) ...
                                 * hy * (st + k_miu * LANDAB(JB, IB)));
                             
                  MC(m, k) = + 0.25 * ss * XNB(JB, IB) * (2 * sinh(0.5 * LANDAB(JB, IB) * hx)/(LANDAB(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st + m_miu * LANDAB(JB, IB)) * XDB(JB, IB) ...
                                 * hy * (st + k_miu * LANDAB(JB, IB)));
                             
                  XC_IN(m, k) = + 0.25 * ss * XNB(JB, IB) * exp(- 0.5 * LANDAB(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDAB(JB, IB)) * XDB(JB, IB) ...
                                 * hy * (st + k_miu * LANDAB(JB, IB)));
                             
                  YB_OUT(m, k) = + 0.25 * ss * YN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st - k_theta * LANDA0(JB, IB)));
                             
                  YB_IN(m, k) = + 0.25 * ss * YN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st - k_theta * LANDA0(JB, IB)));
                             
                  YC_OUT(m, k) = - 0.25 * ss * YNR(JB, IB) * exp(- 0.5 * LANDAR(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDAR(JB, IB)) * YDR(JB, IB) ...
                                 * hx * (st - k_theta * LANDAR(JB, IB)));
                             
                  YC_IN(m, k) = - 0.25 * ss * YNR(JB, IB) * exp(0.5 * LANDAR(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDAR(JB, IB)) * YDR(JB, IB) ...
                                 * hx * (st - k_theta * LANDAR(JB, IB)));
                             
                elseif (k > M / 2 && k <= 3 * M /4) % IIIQ
                  XB_OUT(m, k) = + 0.25 * ss * XN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st + k_miu * LANDA0(JB, IB)));
                             
                  MB(m, k) = + 0.25 * ss * XN0(JB, IB) * (2 * sinh(0.5 * LANDA0(JB, IB) * hx)/(LANDA0(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st + m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st + k_miu * LANDA0(JB, IB)));
                             
                  XB_IN(m, k) = + 0.25 * ss * XN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st + k_miu * LANDA0(JB, IB)));
                             
                  XC_OUT(m, k) = - 0.25 * ss * XNT(JB, IB) * exp(0.5 * LANDAT(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDAT(JB, IB)) * XDT(JB, IB) ...
                                 * hy * (st + k_miu * LANDAT(JB, IB)));
                             
                  MC(m, k) = - 0.25 * ss * XNT(JB, IB) * (2 * sinh(0.5 * LANDAT(JB, IB) * hx)/(LANDAT(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st + m_miu * LANDAT(JB, IB)) * XDT(JB, IB) ...
                                 * hy * (st + k_miu * LANDAT(JB, IB)));
                             
                  XC_IN(m, k) = - 0.25 * ss * XNT(JB, IB) * exp(- 0.5 * LANDAT(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDAT(JB, IB)) * XDT(JB, IB) ...
                                 * hy * (st + k_miu * LANDAT(JB, IB)));
                             
                  YB_OUT(m, k) = + 0.25 * ss * YN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st + k_theta * LANDA0(JB, IB)));
                             
                  YB_IN(m, k) = + 0.25 * ss * YN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st + k_theta * LANDA0(JB, IB)));
                             
                  YC_OUT(m, k) = - 0.25 * ss * YNR(JB, IB) * exp(0.5 * LANDAR(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDAR(JB, IB)) * YDR(JB, IB) ...
                                 * hx * (st + k_theta * LANDAR(JB, IB)));
                             
                  YC_IN(m, k) = - 0.25 * ss * YNR(JB, IB) * exp(- 0.5 * LANDAR(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDAR(JB, IB)) * YDR(JB, IB) ...
                                 * hx * (st + k_theta * LANDAR(JB, IB)));
                             
                elseif (k > 3 * M / 4 && k <= M) % IVQ
                  XB_OUT(m, k) = + 0.25 * ss * XN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st - k_miu * LANDA0(JB, IB)));
                             
                  MB(m, k) = + 0.25 * ss * XN0(JB, IB) * (2 * sinh(0.5 * LANDA0(JB, IB) * hx)/(LANDA0(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st - m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st - k_miu * LANDA0(JB, IB)));
                             
                  XB_IN(m, k) = + 0.25 * ss * XN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st - k_miu * LANDA0(JB, IB)));
                             
                  XC_OUT(m, k) = - 0.25 * ss * XNT(JB, IB) * exp(- 0.5 * LANDAT(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDAT(JB, IB)) * XDT(JB, IB) ...
                                 * hy * (st - k_miu * LANDAT(JB, IB)));
                             
                  MC(m, k) = - 0.25 * ss * XNT(JB, IB) * (2 * sinh(0.5 * LANDAT(JB, IB) * hx)/(LANDAT(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st - m_miu * LANDAT(JB, IB)) * XDT(JB, IB) ...
                                 * hy * (st - k_miu * LANDAT(JB, IB)));
                             
                  XC_IN(m, k) = - 0.25 * ss * XNT(JB, IB) * exp(0.5 * LANDAT(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDAT(JB, IB)) * XDT(JB, IB) ...
                                 * hy * (st - k_miu * LANDAT(JB, IB)));
                             
                  YB_OUT(m, k) = - 0.25 * ss * YN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st + k_theta * LANDA0(JB, IB)));
                             
                  YB_IN(m, k) = - 0.25 * ss * YN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st + k_theta * LANDA0(JB, IB)));
                             
                  YC_OUT(m, k) = + 0.25 * ss * YNL(JB, IB) * exp(0.5 * LANDAL(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDAL(JB, IB)) * YDL(JB, IB) ...
                                 * hx * (st + k_theta * LANDAL(JB, IB)));
                             
                  YC_IN(m, k) = + 0.25 * ss * YNL(JB, IB) * exp(- 0.5 * LANDAL(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDAL(JB, IB)) * YDL(JB, IB) ...
                                 * hx * (st + k_theta * LANDAL(JB, IB)));
                             
                end
            
              end % END LOOP FOR THE COLUMNS (IQ)
              %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
            elseif (m > M / 4 && m <= M / 2) %%%%%%%%%%%%%%%%%%%%%%%%%% IIQ
              for k = 1: M % LOOP FOR THE COLUMNS (IIQ)
                k_miu = QUAD(k, 1); k_theta = QUAD(k, 2); k_w = QUAD(k, 3);
                
                XA(m, k) = xvects(m, k, z) * exp(- 0.5 * st * hx / xvals(k, z));
                XE(m, k) = xvects(m, k, z) * exp(0.5 * st * hx / xvals(k, z));
                YA(m, k) = yvects(m, k, z) * exp(0.5 * st * hy / yvals(k, z));
                YE(m, k) = yvects(m, k, z) * exp(- 0.5 * st * hy / yvals(k, z));
                XM(m, k) = xvects(m, k, z) * xvals(k, z) * 2 * sinh(0.5 * st * hx / xvals(k, z)) / (st * hx);
            
                if (k <= M / 4) % IQ
                  XB_OUT(m, k) = - 0.25 * ss * XN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st - k_miu * LANDA0(JB, IB)));
                             
                  MB(m, k) = - 0.25 * ss * XN0(JB, IB) * (2 * sinh(0.5 * LANDA0(JB, IB) * hx)/(LANDA0(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st - m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st - k_miu * LANDA0(JB, IB)));
                  
                  XB_IN(m, k) = - 0.25 * ss * XN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st - k_miu * LANDA0(JB, IB)));
                             
                  XC_OUT(m, k) = + 0.25 * ss * XNB(JB, IB) * exp(0.5 * LANDAB(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDAB(JB, IB)) * XDB(JB, IB) ...
                                 * hy * (st - k_miu * LANDAB(JB, IB)));
                             
                  MC(m, k) = + 0.25 * ss * XNB(JB, IB) * (2 * sinh(0.5 * LANDAB(JB, IB) * hx)/(LANDAB(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st - m_miu * LANDAB(JB, IB)) * XDB(JB, IB) ...
                                 * hy * (st - k_miu * LANDAB(JB, IB)));
                             
                  XC_IN(m, k) = + 0.25 * ss * XNB(JB, IB) * exp(- 0.5 * LANDAB(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDAB(JB, IB)) * XDB(JB, IB) ...
                                 * hy * (st - k_miu * LANDAB(JB, IB)));
                             
                  YB_OUT(m, k) = - 0.25 * ss * YN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st - k_theta * LANDA0(JB, IB)));
                             
                  YB_IN(m, k) = - 0.25 * ss * YN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st - k_theta * LANDA0(JB, IB)));
                             
                  YC_OUT(m, k) = + 0.25 * ss * YNL(JB, IB) * exp(- 0.5 * LANDAL(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDAL(JB, IB)) * YDL(JB, IB) ...
                                 * hx * (st - k_theta * LANDAL(JB, IB)));
                             
                  YC_IN(m, k) = + 0.25 * ss * YNL(JB, IB) * exp(0.5 * LANDAL(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDAL(JB, IB)) * YDL(JB, IB) ...
                                 * hx * (st - k_theta * LANDAL(JB, IB)));
                             
                elseif (k > M / 4 && k <= M / 2) % IIQ
                  XB_OUT(m, k) = - 0.25 * ss * XN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st + k_miu * LANDA0(JB, IB)));
                  if (k == m) 
                    XB_OUT(m, k) = XB_OUT(m,k) - XN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hx) ...
                                   * m_theta / (hy * (st + m_miu * LANDA0(JB, IB))); 
                  end
                  
                  MB(m, k) = - 0.25 * ss * XN0(JB, IB) * (2 * sinh(0.5 * LANDA0(JB, IB) * hx)/(LANDA0(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st + m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st + k_miu * LANDA0(JB, IB)));
                  if (k == m) 
                    MB(m, k) = MB(m,k) - XN0(JB, IB) * (2 * sinh(0.5 * LANDA0(JB, IB) * hx)/(LANDA0(JB, IB) * hx)) ...
                                   * m_theta / (hy * (st + m_miu * LANDA0(JB, IB))); 
                  end
                  
                  XB_IN(m, k) = - 0.25 * ss * XN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st + k_miu * LANDA0(JB, IB)));
                  if (k == m) 
                    XB_IN(m, k) = XB_IN(m,k) - XN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hx) ...
                                   * m_theta / (hy * (st + m_miu * LANDA0(JB, IB))); 
                  end
                  
                  XC_OUT(m, k) = + 0.25 * ss * XNB(JB, IB) * exp(- 0.5 * LANDAB(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDAB(JB, IB)) * XDB(JB, IB) ...
                                 * hy * (st + k_miu * LANDAB(JB, IB)));
                  if (k == m) 
                    XC_OUT(m, k) = XC_OUT(m,k) + XNB(JB, IB) * exp(- 0.5 * LANDAB(JB, IB) * hx) ...
                                   * m_theta / (hy * (st + m_miu * LANDAB(JB, IB))); 
                  end
                  
                  MC(m, k) = + 0.25 * ss * XNB(JB, IB) * (2 * sinh(0.5 * LANDAB(JB, IB) * hx)/(LANDAB(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st + m_miu * LANDAB(JB, IB)) * XDB(JB, IB) ...
                                 * hy * (st + k_miu * LANDAB(JB, IB)));
                  if (k == m) 
                    MC(m, k) = MC(m,k) + XNB(JB, IB) * (2 * sinh(0.5 * LANDAB(JB, IB) * hx)/(LANDAB(JB, IB) * hx)) ...
                                   * m_theta / (hy * (st + m_miu * LANDAB(JB, IB))); 
                  end
                  
                  XC_IN(m, k) = + 0.25 * ss * XNB(JB, IB) * exp(0.5 * LANDAB(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDAB(JB, IB)) * XDB(JB, IB) ...
                                 * hy * (st + k_miu * LANDAB(JB, IB)));
                  if (k == m) 
                    XC_IN(m, k) = XC_IN(m,k) + XNB(JB, IB) * exp(0.5 * LANDAB(JB, IB) * hx) ...
                                   * m_theta / (hy * (st + m_miu * LANDAB(JB, IB))); 
                  end
                  
                  YB_OUT(m, k) = + 0.25 * ss * YN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st - k_theta * LANDA0(JB, IB)));
                  if (k == m) 
                    YB_OUT(m, k) = YB_OUT(m,k) + YN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hy) ...
                                   * m_miu / (hx * (st - m_theta * LANDA0(JB, IB))); 
                  end
                  
                  YB_IN(m, k) = + 0.25 * ss * YN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st - k_theta * LANDA0(JB, IB)));
                  if (k == m) 
                    YB_IN(m, k) = YB_IN(m,k) + YN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hy) ...
                                   * m_miu / (hx * (st - m_theta * LANDA0(JB, IB))); 
                  end
                  
                  YC_OUT(m, k) = - 0.25 * ss * YNR(JB, IB) * exp(- 0.5 * LANDAR(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDAR(JB, IB)) * YDR(JB, IB) ...
                                 * hx * (st - k_theta * LANDAR(JB, IB)));
                  if (k == m) 
                    YC_OUT(m, k) = YC_OUT(m,k) - YNR(JB, IB) * exp(- 0.5 * LANDAR(JB, IB) * hy) ...
                                   * m_miu / (hx * (st - m_theta * LANDAR(JB, IB))); 
                  end
                  
                  YC_IN(m, k) = - 0.25 * ss * YNR(JB, IB) * exp(0.5 * LANDAR(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDAR(JB, IB)) * YDR(JB, IB) ...
                                 * hx * (st - k_theta * LANDAR(JB, IB)));
                  if (k == m) 
                    YC_IN(m, k) = YC_IN(m,k) - YNR(JB, IB) * exp(0.5 * LANDAR(JB, IB) * hy) ...
                                   * m_miu / (hx * (st - m_theta * LANDAR(JB, IB))); 
                  end
                  
                elseif (k > M / 2 && k <= 3 * M /4) % IIIQ
                  XB_OUT(m, k) = + 0.25 * ss * XN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st + k_miu * LANDA0(JB, IB)));
                             
                  MB(m, k) = + 0.25 * ss * XN0(JB, IB) * (2 * sinh(0.5 * LANDA0(JB, IB) * hx)/(LANDA0(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st + m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st + k_miu * LANDA0(JB, IB)));
                             
                  XB_IN(m, k) = + 0.25 * ss * XN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st + k_miu * LANDA0(JB, IB)));
                             
                  XC_OUT(m, k) = - 0.25 * ss * XNT(JB, IB) * exp(- 0.5 * LANDAT(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDAT(JB, IB)) * XDT(JB, IB) ...
                                 * hy * (st + k_miu * LANDAT(JB, IB)));
                             
                  MC(m, k) = - 0.25 * ss * XNT(JB, IB) * (2 * sinh(0.5 * LANDAT(JB, IB) * hx)/(LANDAT(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st + m_miu * LANDAT(JB, IB)) * XDT(JB, IB) ...
                                 * hy * (st + k_miu * LANDAT(JB, IB)));
                             
                  XC_IN(m, k) = - 0.25 * ss * XNT(JB, IB) * exp(0.5 * LANDAT(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDAT(JB, IB)) * XDT(JB, IB) ...
                                 * hy * (st + k_miu * LANDAT(JB, IB)));
                             
                  YB_OUT(m, k) = + 0.25 * ss * YN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st + k_theta * LANDA0(JB, IB)));
                             
                  YB_IN(m, k) = + 0.25 * ss * YN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st + k_theta * LANDA0(JB, IB)));
                             
                  YC_OUT(m, k) = - 0.25 * ss * YNR(JB, IB) * exp(0.5 * LANDAR(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDAR(JB, IB)) * YDR(JB, IB) ...
                                 * hx * (st + k_theta * LANDAR(JB, IB)));
                             
                  YC_IN(m, k) = - 0.25 * ss * YNR(JB, IB) * exp(- 0.5 * LANDAR(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDAR(JB, IB)) * YDR(JB, IB) ...
                                 * hx * (st + k_theta * LANDAR(JB, IB)));
                             
                elseif (k > 3 * M / 4 && k <= M) % IVQ
                  XB_OUT(m, k) = + 0.25 * ss * XN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st - k_miu * LANDA0(JB, IB)));
                             
                  MB(m, k) = + 0.25 * ss * XN0(JB, IB) * (2 * sinh(0.5 * LANDA0(JB, IB) * hx)/(LANDA0(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st - m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st - k_miu * LANDA0(JB, IB)));
                             
                  XB_IN(m, k) = + 0.25 * ss * XN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st - k_miu * LANDA0(JB, IB)));
                             
                  XC_OUT(m, k) = - 0.25 * ss * XNT(JB, IB) * exp(0.5 * LANDAT(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDAT(JB, IB)) * XDT(JB, IB) ...
                                 * hy * (st - k_miu * LANDAT(JB, IB)));
                             
                  MC(m, k) = - 0.25 * ss * XNT(JB, IB) * (2 * sinh(0.5 * LANDAT(JB, IB) * hx)/(LANDAT(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st - m_miu * LANDAT(JB, IB)) * XDT(JB, IB) ...
                                 * hy * (st - k_miu * LANDAT(JB, IB)));
                             
                  XC_IN(m, k) = - 0.25 * ss * XNT(JB, IB) * exp(- 0.5 * LANDAT(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDAT(JB, IB)) * XDT(JB, IB) ...
                                 * hy * (st - k_miu * LANDAT(JB, IB)));
                            
                  YB_OUT(m, k) = - 0.25 * ss * YN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st + k_theta * LANDA0(JB, IB)));
                             
                  YB_IN(m, k) = - 0.25 * ss * YN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st + k_theta * LANDA0(JB, IB)));
                             
                  YC_OUT(m, k) = + 0.25 * ss * YNL(JB, IB) * exp(0.5 * LANDAL(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDAL(JB, IB)) * YDL(JB, IB) ...
                                 * hx * (st + k_theta * LANDAL(JB, IB)));
                             
                  YC_IN(m, k) = + 0.25 * ss * YNL(JB, IB) * exp(- 0.5 * LANDAL(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDAL(JB, IB)) * YDL(JB, IB) ...
                                 * hx * (st + k_theta * LANDAL(JB, IB)));
                             
                end
              %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
              end % END LOOP FOR THE COLUMNS (IIQ)
            elseif (m > M / 2 && m <= 3 * M / 4) %%%%%%%%%%%%%%%%%%%%% IIIQ
              for k = 1: M % LOOP FOR THE COLUMNS (IIIQ)
                k_miu = QUAD(k, 1); k_theta = QUAD(k, 2); k_w = QUAD(k, 3);
                
                XA(m, k) = xvects(m, k, z) * exp(- 0.5 * st * hx / xvals(k, z));
                XE(m, k) = xvects(m, k, z) * exp(0.5 * st * hx / xvals(k, z));
                YA(m, k) = yvects(m, k, z) * exp(- 0.5 * st * hy / yvals(k, z));
                YE(m, k) = yvects(m, k, z) * exp(0.5 * st * hy / yvals(k, z));
                XM(m, k) = xvects(m, k, z) * xvals(k, z) * 2 * sinh(0.5 * st * hx / xvals(k, z)) / (st * hx);
            
                if (k <= M / 4) % IQ
                  XB_OUT(m, k) = - 0.25 * ss * XN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st - k_miu * LANDA0(JB, IB)));
                             
                  MB(m, k) = - 0.25 * ss * XN0(JB, IB) * (2 * sinh(0.5 * LANDA0(JB, IB) * hx)/(LANDA0(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st - m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st - k_miu * LANDA0(JB, IB)));
                             
                  XB_IN(m, k) = - 0.25 * ss * XN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st - k_miu * LANDA0(JB, IB)));
                             
                  XC_OUT(m, k) = + 0.25 * ss * XNB(JB, IB) * exp(0.5 * LANDAB(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDAB(JB, IB)) * XDB(JB, IB) ...
                                 * hy * (st - k_miu * LANDAB(JB, IB)));
                             
                  MC(m, k) = + 0.25 * ss * XNB(JB, IB) * (2 * sinh(0.5 * LANDAB(JB, IB) * hx)/(LANDAB(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st - m_miu * LANDAB(JB, IB)) * XDB(JB, IB) ...
                                 * hy * (st - k_miu * LANDAB(JB, IB)));
                             
                  XC_IN(m, k) = + 0.25 * ss * XNB(JB, IB) * exp(- 0.5 * LANDAB(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDAB(JB, IB)) * XDB(JB, IB) ...
                                 * hy * (st - k_miu * LANDAB(JB, IB)));
                             
                  YB_OUT(m, k) = - 0.25 * ss * YN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st - k_theta * LANDA0(JB, IB)));
                             
                  YB_IN(m, k) = - 0.25 * ss * YN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st - k_theta * LANDA0(JB, IB)));
                             
                  YC_OUT(m, k) = + 0.25 * ss * YNL(JB, IB) * exp(0.5 * LANDAL(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDAL(JB, IB)) * YDL(JB, IB) ...
                                 * hx * (st - k_theta * LANDAL(JB, IB)));
                             
                  YC_IN(m, k) = + 0.25 * ss * YNL(JB, IB) * exp(- 0.5 * LANDAL(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDAL(JB, IB)) * YDL(JB, IB) ...
                                 * hx * (st - k_theta * LANDAL(JB, IB)));
                  
                elseif (k > M / 4 && k <= M / 2) % IIQ
                  XB_OUT(m, k) = - 0.25 * ss * XN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st + k_miu * LANDA0(JB, IB)));
                             
                  MB(m, k) = - 0.25 * ss * XN0(JB, IB) * (2 * sinh(0.5 * LANDA0(JB, IB) * hx)/(LANDA0(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st + m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st + k_miu * LANDA0(JB, IB)));
                  
                  XB_IN(m, k) = - 0.25 * ss * XN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st + k_miu * LANDA0(JB, IB)));
                             
                  XC_OUT(m, k) = + 0.25 * ss * XNB(JB, IB) * exp(- 0.5 * LANDAB(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDAB(JB, IB)) * XDB(JB, IB) ...
                                 * hy * (st + k_miu * LANDAB(JB, IB)));
                             
                  MC(m, k) = + 0.25 * ss * XNB(JB, IB) * (2 * sinh(0.5 * LANDAB(JB, IB) * hx)/(LANDAB(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st + m_miu * LANDAB(JB, IB)) * XDB(JB, IB) ...
                                 * hy * (st + k_miu * LANDAB(JB, IB)));
                             
                  XC_IN(m, k) = + 0.25 * ss * XNB(JB, IB) * exp(0.5 * LANDAB(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDAB(JB, IB)) * XDB(JB, IB) ...
                                 * hy * (st + k_miu * LANDAB(JB, IB)));
                             
                  YB_OUT(m, k) = + 0.25 * ss * YN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st - k_theta * LANDA0(JB, IB)));
                             
                  YB_IN(m, k) = + 0.25 * ss * YN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st - k_theta * LANDA0(JB, IB)));
                             
                  YC_OUT(m, k) = - 0.25 * ss * YNR(JB, IB) * exp(0.5 * LANDAR(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDAR(JB, IB)) * YDR(JB, IB) ...
                                 * hx * (st - k_theta * LANDAR(JB, IB)));
                             
                  YC_IN(m, k) = - 0.25 * ss * YNR(JB, IB) * exp(- 0.5 * LANDAR(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDAR(JB, IB)) * YDR(JB, IB) ...
                                 * hx * (st - k_theta * LANDAR(JB, IB)));
                             
                elseif (k > M / 2 && k <= 3 * M /4) % IIIQ
                  XB_OUT(m, k) = + 0.25 * ss * XN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st + k_miu * LANDA0(JB, IB)));
                  if (k == m) 
                    XB_OUT(m, k) = XB_OUT(m,k) + XN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hx) ...
                                   * m_theta / (hy * (st + m_miu * LANDA0(JB, IB))); 
                  end
                  
                  MB(m, k) = + 0.25 * ss * XN0(JB, IB) * (2 * sinh(0.5 * LANDA0(JB, IB) * hx)/(LANDA0(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st + m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st + k_miu * LANDA0(JB, IB)));
                  if (k == m) 
                    MB(m, k) = MB(m,k) + XN0(JB, IB) * (2 * sinh(0.5 * LANDA0(JB, IB) * hx)/(LANDA0(JB, IB) * hx)) ...
                                   * m_theta / (hy * (st + m_miu * LANDA0(JB, IB))); 
                  end
                  
                  XB_IN(m, k) = + 0.25 * ss * XN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st + k_miu * LANDA0(JB, IB)));
                  if (k == m) 
                    XB_IN(m, k) = XB_IN(m,k) + XN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hx) ...
                                   * m_theta / (hy * (st + m_miu * LANDA0(JB, IB))); 
                  end
                  
                  XC_OUT(m, k) = - 0.25 * ss * XNT(JB, IB) * exp(- 0.5 * LANDAT(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDAT(JB, IB)) * XDT(JB, IB) ...
                                 * hy * (st + k_miu * LANDAT(JB, IB)));
                  if (k == m) 
                    XC_OUT(m, k) = XC_OUT(m,k) - XNT(JB, IB) * exp(- 0.5 * LANDAT(JB, IB) * hx) ...
                                   * m_theta / (hy * (st + m_miu * LANDAT(JB, IB))); 
                  end
                  
                  MC(m, k) = - 0.25 * ss * XNT(JB, IB) * (2 * sinh(0.5 * LANDAT(JB, IB) * hx)/(LANDAT(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st + m_miu * LANDAT(JB, IB)) * XDT(JB, IB) ...
                                 * hy * (st + k_miu * LANDAT(JB, IB)));
                  if (k == m) 
                    MC(m, k) = MC(m,k) - XNT(JB, IB) * (2 * sinh(0.5 * LANDAT(JB, IB) * hx)/(LANDAT(JB, IB) * hx)) ...
                                   * m_theta / (hy * (st + m_miu * LANDAT(JB, IB))); 
                  end
                  
                  XC_IN(m, k) = - 0.25 * ss * XNT(JB, IB) * exp(0.5 * LANDAT(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDAT(JB, IB)) * XDT(JB, IB) ...
                                 * hy * (st + k_miu * LANDAT(JB, IB)));
                  if (k == m) 
                    XC_IN(m, k) = XC_IN(m,k) - XNT(JB, IB) * exp(0.5 * LANDAT(JB, IB) * hx) ...
                                   * m_theta / (hy * (st + m_miu * LANDAT(JB, IB))); 
                  end
                  
                  YB_OUT(m, k) = + 0.25 * ss * YN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st + k_theta * LANDA0(JB, IB)));
                  if (k == m) 
                    YB_OUT(m, k) = YB_OUT(m,k) + YN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hy) ...
                                   * m_miu / (hx * (st + m_theta * LANDA0(JB, IB))); 
                  end
                  
                  YB_IN(m, k) = + 0.25 * ss * YN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st + k_theta * LANDA0(JB, IB)));
                  if (k == m) 
                    YB_IN(m, k) = YB_IN(m,k) + YN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hy) ...
                                   * m_miu / (hx * (st + m_theta * LANDA0(JB, IB))); 
                  end
                  
                  YC_OUT(m, k) = - 0.25 * ss * YNR(JB, IB) * exp(- 0.5 * LANDAR(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDAR(JB, IB)) * YDR(JB, IB) ...
                                 * hx * (st + k_theta * LANDAR(JB, IB)));
                  if (k == m) 
                    YC_OUT(m, k) = YC_OUT(m,k) - YNR(JB, IB) * exp(- 0.5 * LANDAR(JB, IB) * hy) ...
                                   * m_miu / (hx * (st + m_theta * LANDAR(JB, IB))); 
                  end
                  
                  YC_IN(m, k) = - 0.25 * ss * YNR(JB, IB) * exp(0.5 * LANDAR(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDAR(JB, IB)) * YDR(JB, IB) ...
                                 * hx * (st + k_theta * LANDAR(JB, IB)));
                  if (k == m) 
                    YC_IN(m, k) = YC_IN(m,k) - YNR(JB, IB) * exp(0.5 * LANDAR(JB, IB) * hy) ...
                                   * m_miu / (hx * (st + m_theta * LANDAR(JB, IB))); 
                  end
                  
                elseif (k > 3 * M / 4 && k <= M) % IVQ
                  XB_OUT(m, k) = + 0.25 * ss * XN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st - k_miu * LANDA0(JB, IB)));
                             
                  MB(m, k) = + 0.25 * ss * XN0(JB, IB) * (2 * sinh(0.5 * LANDA0(JB, IB) * hx)/(LANDA0(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st - m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st - k_miu * LANDA0(JB, IB)));
                             
                  XB_IN(m, k) = + 0.25 * ss * XN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st - k_miu * LANDA0(JB, IB)));
                  
                  XC_OUT(m, k) = - 0.25 * ss * XNT(JB, IB) * exp(0.5 * LANDAT(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDAT(JB, IB)) * XDT(JB, IB) ...
                                 * hy * (st - k_miu * LANDAT(JB, IB)));
                             
                  MC(m, k) = - 0.25 * ss * XNT(JB, IB) * (2 * sinh(0.5 * LANDAT(JB, IB) * hx)/(LANDAT(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st - m_miu * LANDAT(JB, IB)) * XDT(JB, IB) ...
                                 * hy * (st - k_miu * LANDAT(JB, IB)));
                             
                  XC_IN(m, k) = - 0.25 * ss * XNT(JB, IB) * exp(- 0.5 * LANDAT(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDAT(JB, IB)) * XDT(JB, IB) ...
                                 * hy * (st - k_miu * LANDAT(JB, IB)));
                             
                  YB_OUT(m, k) = - 0.25 * ss * YN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st + k_theta * LANDA0(JB, IB)));
                             
                  YB_OUT(m, k) = - 0.25 * ss * YN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st + k_theta * LANDA0(JB, IB)));
                             
                  YC_OUT(m, k) = + 0.25 * ss * YNL(JB, IB) * exp(- 0.5 * LANDAL(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDAL(JB, IB)) * YDL(JB, IB) ...
                                 * hx * (st + k_theta * LANDAL(JB, IB)));
                             
                  YC_OUT(m, k) = + 0.25 * ss * YNL(JB, IB) * exp(0.5 * LANDAL(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDAL(JB, IB)) * YDL(JB, IB) ...
                                 * hx * (st + k_theta * LANDAL(JB, IB)));
                             
                end
              %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
              end % END LOOP FOR THE COLUMNS (IIIQ)
            elseif (m > 3 * M / 4 && m <= M) %%%%%%%%%%%%%%%%%%%%%%%%%% IVQ
              for k = 1: M % LOOP FOR THE COLUMNS (IVQ)
                k_miu = QUAD(k, 1); k_theta = QUAD(k, 2); k_w = QUAD(k, 3);
                
                XA(m, k) = xvects(m, k, z) * exp(0.5 * st * hx / xvals(k, z));
                XE(m, k) = xvects(m, k, z) * exp(- 0.5 * st * hx / xvals(k, z));
                YA(m, k) = yvects(m, k, z) * exp(- 0.5 * st * hy / yvals(k, z));
                YE(m, k) = yvects(m, k, z) * exp(0.5 * st * hy / yvals(k, z));
                XM(m, k) = xvects(m, k, z) * xvals(k, z) * 2 * sinh(0.5 * st * hx / xvals(k, z)) / (st * hx);
            
                if (k <= M / 4) % IQ
                  XB_OUT(m, k) = - 0.25 * ss * XN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st - k_miu * LANDA0(JB, IB)));
                             
                  MB(m, k) = - 0.25 * ss * XN0(JB, IB) * (2 * sinh(0.5 * LANDA0(JB, IB) * hx)/(LANDA0(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st - m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st - k_miu * LANDA0(JB, IB)));
                             
                  XB_IN(m, k) = - 0.25 * ss * XN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st - k_miu * LANDA0(JB, IB)));
                             
                  XC_OUT(m, k) = + 0.25 * ss * XNB(JB, IB) * exp(- 0.5 * LANDAB(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDAB(JB, IB)) * XDB(JB, IB) ...
                                 * hy * (st - k_miu * LANDAB(JB, IB)));
                             
                  MC(m, k) = + 0.25 * ss * XNB(JB, IB) * (2 * sinh(0.5 * LANDAB(JB, IB) * hx)/(LANDAB(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st - m_miu * LANDAB(JB, IB)) * XDB(JB, IB) ...
                                 * hy * (st - k_miu * LANDAB(JB, IB)));
                             
                  XC_IN(m, k) = + 0.25 * ss * XNB(JB, IB) * exp(0.5 * LANDAB(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDAB(JB, IB)) * XDB(JB, IB) ...
                                 * hy * (st - k_miu * LANDAB(JB, IB)));
                             
                  YB_OUT(m, k) = - 0.25 * ss * YN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st - k_theta * LANDA0(JB, IB)));
                             
                  YB_IN(m, k) = - 0.25 * ss * YN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st - k_theta * LANDA0(JB, IB)));
                             
                  YC_OUT(m, k) = + 0.25 * ss * YNL(JB, IB) * exp(0.5 * LANDAL(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDAL(JB, IB)) * YDL(JB, IB) ...
                                 * hx * (st - k_theta * LANDAL(JB, IB)));
                             
                  YC_IN(m, k) = + 0.25 * ss * YNL(JB, IB) * exp(- 0.5 * LANDAL(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDAL(JB, IB)) * YDL(JB, IB) ...
                                 * hx * (st - k_theta * LANDAL(JB, IB)));
                  
                elseif (k > M / 4 && k <= M / 2) % IIQ
                  XB_OUT(m, k) = - 0.25 * ss * XN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st + k_miu * LANDA0(JB, IB)));
                             
                  MB(m, k) = - 0.25 * ss * XN0(JB, IB) * (2 * sinh(0.5 * LANDA0(JB, IB) * hx)/(LANDA0(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st + m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st + k_miu * LANDA0(JB, IB)));
                             
                  XB_IN(m, k) = - 0.25 * ss * XN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st + k_miu * LANDA0(JB, IB)));
                             
                  XC_OUT(m, k) = + 0.25 * ss * XNB(JB, IB) * exp(0.5 * LANDAB(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDAB(JB, IB)) * XDB(JB, IB) ...
                                 * hy * (st + k_miu * LANDAB(JB, IB)));
                             
                  MC(m, k) = + 0.25 * ss * XNB(JB, IB) * (2 * sinh(0.5 * LANDAB(JB, IB) * hx)/(LANDAB(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st + m_miu * LANDAB(JB, IB)) * XDB(JB, IB) ...
                                 * hy * (st + k_miu * LANDAB(JB, IB)));
                             
                  XC_IN(m, k) = + 0.25 * ss * XNB(JB, IB) * exp(- 0.5 * LANDAB(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDAB(JB, IB)) * XDB(JB, IB) ...
                                 * hy * (st + k_miu * LANDAB(JB, IB)));
                             
                  YB_OUT(m, k) = + 0.25 * ss * YN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st - k_theta * LANDA0(JB, IB)));
                             
                  YB_IN(m, k) = + 0.25 * ss * YN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st - k_theta * LANDA0(JB, IB)));
                             
                  YC_OUT(m, k) = - 0.25 * ss * YNR(JB, IB) * exp(0.5 * LANDAR(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDAR(JB, IB)) * YDR(JB, IB) ...
                                 * hx * (st - k_theta * LANDAR(JB, IB)));
                             
                  YC_IN(m, k) = - 0.25 * ss * YNR(JB, IB) * exp(- 0.5 * LANDAR(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st - m_theta * LANDAR(JB, IB)) * YDR(JB, IB) ...
                                 * hx * (st - k_theta * LANDAR(JB, IB)));
                  
                elseif (k > M / 2 && k <= 3 * M /4) % IIIQ
                  XB_OUT(m, k) = + 0.25 * ss * XN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st + k_miu * LANDA0(JB, IB)));
                             
                  MB(m, k) = + 0.25 * ss * XN0(JB, IB) * (2 * sinh(0.5 * LANDA0(JB, IB) * hx)/(LANDA0(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st + m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st + k_miu * LANDA0(JB, IB)));
                             
                  XB_IN(m, k) = + 0.25 * ss * XN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st + k_miu * LANDA0(JB, IB)));
                             
                  XC_OUT(m, k) = - 0.25 * ss * XNT(JB, IB) * exp(0.5 * LANDAT(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDAT(JB, IB)) * XDT(JB, IB) ...
                                 * hy * (st + k_miu * LANDAT(JB, IB)));
                             
                  MC(m, k) = - 0.25 * ss * XNT(JB, IB) * (2 * sinh(0.5 * LANDAT(JB, IB) * hx)/(LANDAT(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st + m_miu * LANDAT(JB, IB)) * XDT(JB, IB) ...
                                 * hy * (st + k_miu * LANDAT(JB, IB)));
                             
                  XC_IN(m, k) = - 0.25 * ss * XNT(JB, IB) * exp(- 0.5 * LANDAT(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st + m_miu * LANDAT(JB, IB)) * XDT(JB, IB) ...
                                 * hy * (st + k_miu * LANDAT(JB, IB)));
                             
                  YB_OUT(m, k) = + 0.25 * ss * YN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st + k_theta * LANDA0(JB, IB)));
                             
                  YB_IN(m, k) = + 0.25 * ss * YN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st + k_theta * LANDA0(JB, IB)));
                             
                  YC_OUT(m, k) = - 0.25 * ss * YNR(JB, IB) * exp(- 0.5 * LANDAR(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDAR(JB, IB)) * YDR(JB, IB) ...
                                 * hx * (st + k_theta * LANDAR(JB, IB)));
                             
                  YC_IN(m, k) = - 0.25 * ss * YNR(JB, IB) * exp(0.5 * LANDAR(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDAR(JB, IB)) * YDR(JB, IB) ...
                                 * hx * (st + k_theta * LANDAR(JB, IB)));
                  
                elseif (k > 3 * M / 4 && k <= M) % IVQ
                  XB_OUT(m, k) = + 0.25 * ss * XN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st - k_miu * LANDA0(JB, IB)));
                  if (k == m) 
                    XB_OUT(m, k) = XB_OUT(m,k) + XN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hx) ...
                                   * m_theta / (hy * (st - m_miu * LANDA0(JB, IB))); 
                  end
                  
                  MB(m, k) = + 0.25 * ss * XN0(JB, IB) * (2 * sinh(0.5 * LANDA0(JB, IB) * hx)/(LANDA0(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st - m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st - k_miu * LANDA0(JB, IB)));
                  if (k == m) 
                    MB(m, k) = MB(m,k) + XN0(JB, IB) * (2 * sinh(0.5 * LANDA0(JB, IB) * hx)/(LANDA0(JB, IB) * hx)) ...
                                   * m_theta / (hy * (st - m_miu * LANDA0(JB, IB))); 
                  end
                  
                  XB_IN(m, k) = + 0.25 * ss * XN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDA0(JB, IB)) * XD0(JB, IB) ...
                                 * hy * (st - k_miu * LANDA0(JB, IB)));
                  if (k == m) 
                    XB_IN(m, k) = XB_IN(m,k) + XN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hx) ...
                                   * m_theta / (hy * (st - m_miu * LANDA0(JB, IB))); 
                  end
                  
                  XC_OUT(m, k) = - 0.25 * ss * XNT(JB, IB) * exp(- 0.5 * LANDAT(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDAT(JB, IB)) * XDT(JB, IB) ...
                                 * hy * (st - k_miu * LANDAT(JB, IB)));
                  if (k == m) 
                    XC_OUT(m, k) = XC_OUT(m,k) - XNT(JB, IB) * exp(- 0.5 * LANDAT(JB, IB) * hx) ...
                                   * m_theta / (hy * (st - m_miu * LANDAT(JB, IB))); 
                  end
                  
                  MC(m, k) = - 0.25 * ss * XNT(JB, IB) * (2 * sinh(0.5 * LANDAT(JB, IB) * hx)/(LANDAT(JB, IB) * hx)) ...
                                 * k_theta * k_w / ((st - m_miu * LANDAT(JB, IB)) * XDT(JB, IB) ...
                                 * hy * (st - k_miu * LANDAT(JB, IB)));
                  if (k == m) 
                    MC(m, k) = MC(m,k) - XNT(JB, IB) * (2 * sinh(0.5 * LANDAT(JB, IB) * hx)/(LANDAT(JB, IB) * hx)) ...
                                   * m_theta / (hy * (st - m_miu * LANDAT(JB, IB))); 
                  end
                  
                  XC_IN(m, k) = - 0.25 * ss * XNT(JB, IB) * exp(0.5 * LANDAT(JB, IB) * hx) ...
                                 * k_theta * k_w / ((st - m_miu * LANDAT(JB, IB)) * XDT(JB, IB) ...
                                 * hy * (st - k_miu * LANDAT(JB, IB)));
                  if (k == m) 
                    XC_IN(m, k) = XC_IN(m,k) - XNT(JB, IB) * exp(0.5 * LANDAT(JB, IB) * hx) ...
                                   * m_theta / (hy * (st - m_miu * LANDAT(JB, IB))); 
                  end
                  
                  YB_OUT(m, k) = - 0.25 * ss * YN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st + k_theta * LANDA0(JB, IB)));
                  if (k == m) 
                    YB_OUT(m, k) = YB_OUT(m,k) - YN0(JB, IB) * exp(- 0.5 * LANDA0(JB, IB) * hy) ...
                                   * m_miu / (hx * (st + m_theta * LANDA0(JB, IB))); 
                  end
                  
                  YB_IN(m, k) = - 0.25 * ss * YN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDA0(JB, IB)) * YD0(JB, IB) ...
                                 * hx * (st + k_theta * LANDA0(JB, IB)));
                  if (k == m) 
                    YB_IN(m, k) = YB_IN(m,k) - YN0(JB, IB) * exp(0.5 * LANDA0(JB, IB) * hy) ...
                                   * m_miu / (hx * (st + m_theta * LANDA0(JB, IB))); 
                  end
                  
                  YC_OUT(m, k) = + 0.25 * ss * YNL(JB, IB) * exp(- 0.5 * LANDAL(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDAL(JB, IB)) * YDL(JB, IB) ...
                                 * hx * (st + k_theta * LANDAL(JB, IB)));
                  if (k == m) 
                    YC_OUT(m, k) = YC_OUT(m,k) + YNL(JB, IB) * exp(- 0.5 * LANDAL(JB, IB) * hy) ...
                                   * m_miu / (hx * (st + m_theta * LANDAL(JB, IB))); 
                  end
                  
                  YC_IN(m, k) = + 0.25 * ss * YNL(JB, IB) * exp(0.5 * LANDAL(JB, IB) * hy) ...
                                 * k_miu * k_w / ((st + m_theta * LANDAL(JB, IB)) * YDL(JB, IB) ...
                                 * hx * (st + k_theta * LANDAL(JB, IB)));
                  if (k == m) 
                    YC_IN(m, k) = YC_IN(m,k) + YNL(JB, IB) * exp(0.5 * LANDAL(JB, IB) * hy) ...
                                   * m_miu / (hx * (st + m_theta * LANDAL(JB, IB))); 
                  end
                             
                end
              %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
              end % END LOOP FOR THE COLUMNS (IVQ)
            end 
            
            % H COLUMN VECTOR
            H(m) = Q / (st * (1 - c0));
            
          end %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% % END LOOP FOR THE ROWS
    
          XE_INV = inv(XE); YE_INV = inv(YE);
      
          % RESPONSE MATRIX FOR RECONSTRUCTION
          RM(:, :, JB, IB) = XM * XE_INV;
      
          % LEAKAGE MATRIX FOR RECONSTRUCTION 1
          LM1(:, :, JB, IB) = MB - XM * (XE_INV * XB_IN);
          
          % LEAKAGE MATRIX FOR RECONSTRUCTION 2
          LM2(:, :, JB, IB) = MC - XM * (XE_INV * XC_IN);
      
          % SOURCE VECTOR FRO RECONSTRUCTION
          PM(:, JB, IB) = (IDEN - XM * XE_INV) * H;
      
          AUX = [           IDEN                     , (- (XB_OUT - XA * (XE_INV * XB_IN)));
                 (- (YB_OUT - YA * (YE_INV * YB_IN))),              IDEN                  ];
      
          AUX_INV = inv(AUX);
      
          AUX2 = [        (XA * XE_INV)               , (- (XC_OUT - XA * (XE_INV * XC_IN)));
                  (- (YC_OUT - YA * (YE_INV * YC_IN))),           (YA * YE_INV)            ];
      
          % RESPONSE MATRIX
          R(:, :, JB, IB) = AUX_INV * AUX2;
      
          AUX3 = [(I - XA * XE_INV),    zeros(M, M)    ;
                    zeros(M, M)    , (I - YA * YE_INV)];
      
          S = [H; H];
      
          % CALCULATE THE SOURCE VECTOR
          P(:, JB, IB) = AUX_INV * (AUX3 * S);
          
        end % END LOOP i = 1: ncx
      end % END LOOP rx = 1: NRX
    
    end % END LOOP j = 1: ncy
  end % END LOOP ry = 1: NRY
  
end